regulzen_regulation:
    resource: "@RegulzenRegulationBundle/Controller/"
    type:     annotation
    prefix:   /

regulzen_admin:
    resource: "@RegulzenAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

regulzen_customer_service:
    resource: "@RegulzenCustomerServiceBundle/Controller/"
    type:     annotation
    prefix:   /customer_service

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

