novactive_admin:
    resource: "@NovactiveAdminBundle/Controller/"
    type:     annotation
    prefix:   /

novactive_interface:
    resource: "@NovactiveInterfaceBundle/Controller/"
    type:     annotation
    prefix:   /

